"""Constants for the Mikrotik Control integration."""
from homeassistant.const import Platform

DOMAIN = "mikrotik_control"

# Configuration keys
CONF_USE_SSL = "use_ssl"
CONF_VERIFY_SSL = "verify_ssl"
CONF_ENABLE_INTERFACE_DETAILS = "enable_interface_details"
CONF_ENABLE_INTERFACE_CONTROLS = "enable_interface_controls"
CONF_ENABLE_FIREWALL_CONTROLS = "enable_firewall_controls"
CONF_ENABLE_SCRIPT_BUTTONS = "enable_script_buttons"
CONF_ENABLE_CONTAINER_CONTROLS = "enable_container_controls"
CONF_ENABLE_REBOOT_BUTTON = "enable_reboot_button"
CONF_ENTITY_PRESET = "entity_preset"
CONF_ENABLE_SAFE_MODE = "enable_safe_mode"
CONF_BACKUP_BEFORE_RISKY_ACTIONS = "backup_before_risky_actions"
CONF_ENABLE_WIREGUARD = "enable_wireguard"
CONF_ENABLE_NETWATCH = "enable_netwatch"
CONF_ENABLE_HEALTH_SCORE = "enable_health_score"
CONF_ENABLE_CONFIG_AUDIT = "enable_config_audit"
CONF_ENABLE_FIREWALL_PROFILES = "enable_firewall_profiles"
CONF_FIREWALL_PROFILE_PREFIX = "firewall_profile_prefix"

PRESET_MINIMAL = "minimal"
PRESET_RECOMMENDED = "recommended"
PRESET_ADVANCED = "advanced"
PRESET_FULL = "full"
ENTITY_PRESETS = [
    PRESET_MINIMAL,
    PRESET_RECOMMENDED,
    PRESET_ADVANCED,
    PRESET_FULL,
]

# Defaults
DEFAULT_PORT = 8728
DEFAULT_PORT_SSL = 8729
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_ENABLE_INTERFACE_DETAILS = False
DEFAULT_ENABLE_INTERFACE_CONTROLS = False
DEFAULT_ENABLE_FIREWALL_CONTROLS = False
DEFAULT_ENABLE_SCRIPT_BUTTONS = False
DEFAULT_ENABLE_CONTAINER_CONTROLS = True
DEFAULT_ENABLE_REBOOT_BUTTON = False
DEFAULT_ENTITY_PRESET = PRESET_RECOMMENDED
DEFAULT_ENABLE_SAFE_MODE = True
DEFAULT_BACKUP_BEFORE_RISKY_ACTIONS = False
DEFAULT_ENABLE_WIREGUARD = True
DEFAULT_ENABLE_NETWATCH = True
DEFAULT_ENABLE_HEALTH_SCORE = True
DEFAULT_ENABLE_CONFIG_AUDIT = True
DEFAULT_ENABLE_FIREWALL_PROFILES = True
DEFAULT_FIREWALL_PROFILE_PREFIX = "ha:"

# Platforms
PLATFORMS = [
    Platform.SENSOR,
    Platform.BINARY_SENSOR,
    Platform.SWITCH,
    Platform.BUTTON,
    Platform.UPDATE,
]

# Service Names / Attributes
ATTR_SCRIPT_NAME = "script_name"
SERVICE_RUN_SCRIPT = "run_script"
